apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
  name: {{ include "fullname" . }}
  namespace: {{ template "namespace" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ $.Values.service.type | quote }}
  ports:
    - name: exporter
      port: {{ $.Values.service.port }}
      protocol: TCP
      targetPort: exporter
  selector:
    {{- include "matchLabels" . | nindent 4 }}
